# This file specifies the Rust version used to develop and test the
# tree sitter based extractors.
# It is set to the lowest version of Rust we want to support.

[toolchain]
channel = "1.78"
profile = "minimal"
components = [ "clippy", "rustfmt" ]
