// generated by codegen, do not edit
/**
 * This module provides the public class `CrateModule`.
 */

private import internal.CrateModuleImpl
import codeql.rust.elements.ModuleContainer
import codeql.rust.elements.ValueItem

final class CrateModule = Impl::CrateModule;
