// generated by codegen, do not edit
/**
 * This module provides the public class `ValueItem`.
 */

private import internal.ValueItemImpl
import codeql.rust.elements.Element
import codeql.rust.elements.TypeRepr

final class ValueItem = Impl::ValueItem;
