// generated by codegen, do not edit
/**
 * This module provides the public class `VariantData`.
 */

private import internal.VariantDataImpl
import codeql.rust.elements.Element
import codeql.rust.elements.TypeRepr

final class VariantData = Impl::VariantData;
