# This file specifies the Rust version used to develop and test the rust
# extractor. It will in general be set to the latest rust toolchain, as
# that is what is required by rust-analyzer.

[toolchain]
channel = "1.84"
profile = "minimal"
components = [ "clippy", "rustfmt" ]
